2023-02-17 14:22:01,511 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong HTTP URL specified
2023-02-17 14:22:01,512 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\telega\main.py", line 51, in review
    bot.send_document(message.chat.id, 'sample_decoded.pdf')
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 2082, in send_document
    apihelper.send_data(
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 940, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong HTTP URL specified

2023-02-21 13:42:14,923 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: failed to get HTTP URL content
2023-02-21 13:42:14,924 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\telega\main.py", line 49, in review
    bot.send_document(message.chat.id, chat_id + '.pdf')
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 2082, in send_document
    apihelper.send_data(
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 940, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: failed to get HTTP URL content

2023-02-21 13:43:23,295 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified
2023-02-21 13:43:23,296 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\telega\main.py", line 49, in review
    bot.send_document(message.chat.id, chat_id + '.pdf')
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 2082, in send_document
    apihelper.send_data(
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 940, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified

2023-02-21 13:44:30,219 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified
2023-02-21 13:44:30,219 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\telega\main.py", line 49, in review
    bot.send_document(message.chat.id, chat + '.pdf')
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 2082, in send_document
    apihelper.send_data(
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 940, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified

2023-02-21 13:46:17,887 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified
2023-02-21 13:46:17,888 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\telega\main.py", line 50, in review
    bot.send_document(message.chat.id, talon_send)
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 2082, in send_document
    apihelper.send_data(
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 940, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified

2023-02-21 14:07:42,964 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: failed to get HTTP URL content
2023-02-21 14:07:42,964 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\telega\main.py", line 51, in review
    bot.send_document(message.chat.id, talon_send)
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\__init__.py", line 2082, in send_document
    apihelper.send_data(
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 940, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\telega\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: failed to get HTTP URL content

